name: decypharr

services:
  decypharr:
    container_name: decypharr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8282:8282
    volumes:
      - /mnt/:/mnt:rshared
      - ./data:/data
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined